; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool v3.5.8 on Fri Dec 20 2024 14:59:53 GMT+0100 (Central European Standard Time)

M98 P"homeX.g"
M400
M98 P"homeY.g"
M400
M98 P"homeZ.g"
M400
