; pause.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.5.8 on Fri Dec 20 2024 14:59:54 GMT+0100 (Central European Standard Time)
M83 ; relative extruder moves
G1 E-4 F3600 ; retract 10mm of filament
G91 ; relative positioning
G1 Z25 U25 V25 F360 ; lift Z by 5mm  ; modified to prevent collision between nozzle and buildplate
G90 ; absolute positioning
;G1 X0 Y0 F6000 ; go to X=0 Y=0
