; resume.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.5.8 on Fri Dec 20 2024 14:59:54 GMT+0100 (Central European Standard Time)
G1 R1 X0 Y0 Z25 U25 V25 F600 ; go to 5mm above position of the last move
G1 R1 X0 Y0 Z0 ; go back to the last print move
M83 ; relative extruder moves
G1 E4 F3600 ; extrude 10mm of filament
