; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.5.8 on Fri Dec 20 2024 14:59:54 GMT+0100 (Central European Standard Time)

M116 P0 ; wait for tool temperatures to be reached
